import 'dart:async';
import 'dart:convert';
import 'package:albadael/Constant/api.dart';
import 'package:albadael/Constant/statusCode.dart';
import 'package:albadael/Models/About-Us/autogenerated_about-us.dart';
import 'package:albadael/Models/Home/autogenerated.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

//// get data from api public
Future<Autogenerated> readdata() async {
  final http.Response response = await http.get(Uri.parse(API.publicAPI));
  if (response.statusCode == StatusCode.statusCodeSuccess) {
    return Autogenerated.fromJson(jsonDecode(response.body));
  } else {
    throw Exception('Failed to load API Public');
  }
}

//// get data from api team
Future<Autogenerated_team> readdatateam() async {
  final http.Response response = await http.get(Uri.parse(API.teamAPI));
  if (response.statusCode == StatusCode.statusCodeSuccess) {
    return Autogenerated_team.fromJson(jsonDecode(response.body));
  } else {
    throw Exception('Failed to load API Team');
  }
}

//// get image from locale storge api

String frommater(String url) {
  return API.localstorgeAPI + url;
}

NetworkImage getimage(String name) {
  // ignore: unnecessary_string_interpolations
  final String url = frommater('$name');
  return NetworkImage(url);
}
