import 'data.dart';

class Autogenerated {
  String status;
  String statusCode;
  Null error;
  Data data;

  Autogenerated(
      {required this.status,
      required this.statusCode,
      required this.error,
      required this.data});

  factory Autogenerated.fromJson(Map<String, dynamic> json) {
    return Autogenerated(
        status: json['status'],
        statusCode: json['statusCode'],
        error: json['error'],
        data: json['data'] = new Data.fromJson(json['data']));
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    data['statusCode'] = this.statusCode;
    data['error'] = this.error;
    if (this.data != null) {
      data['data'] = this.data.toJson();
    }
    return data;
  }
}
