import 'package:albadael/Constant/api_connection.dart';
import 'package:albadael/Models/About-Us/autogenerated_about-us.dart';
import 'package:carousel_slider/carousel_options.dart';
import 'package:carousel_slider/carousel_slider.dart';
import 'package:flutter/material.dart';

class Section_Team extends StatefulWidget {
  const Section_Team({Key? key}) : super(key: key);

  @override
  _Section_TeamState createState() => _Section_TeamState();
}

// ignore: camel_case_types
class _Section_TeamState extends State<Section_Team> {
  late Future<Autogenerated_team> datateam;
  @override
  void initState() {
    super.initState();

    datateam = readdatateam();
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<Autogenerated_team>(
        future: datateam,
        builder: (context, snapshot) {
          if (snapshot.hasData) {
            return Column(children: [
              Padding(
                padding: const EdgeInsets.only(top: 8, bottom: 8),
                child: CarouselSlider.builder(
                  itemCount: snapshot.data!.data.team.length,
                  itemBuilder:
                      (BuildContext context, int itemIndex, int pageViewIndex) {
                    return Container(
                      decoration: BoxDecoration(
                          color: Colors.grey[200],
                          borderRadius: BorderRadius.all(Radius.circular(10))),
                      width: MediaQuery.of(context).size.width,
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          CircleAvatar(
                            radius: 80,
                            backgroundImage: getimage(snapshot
                                .data!.data.team[itemIndex].photo
                                .toString()),
                          ),
                          SizedBox(
                            height: 30,
                          ),
                          Text(snapshot.data!.data.team[itemIndex].name,
                              style: TextStyle(fontWeight: FontWeight.bold)),
                          SizedBox(
                            height: 10,
                          ),
                          Text(
                            snapshot.data!.data.team[itemIndex].position,
                          ),
                        ],
                      ),
                    );
                  },
                  options: CarouselOptions(
                    height: 300,
                    aspectRatio: 16 / 9,
                    viewportFraction: 0.8,
                    initialPage: 0,
                    enableInfiniteScroll: true,
                    reverse: false,
                    autoPlay: true,
                    autoPlayInterval: Duration(seconds: 4),
                    autoPlayAnimationDuration: Duration(milliseconds: 800),
                    autoPlayCurve: Curves.fastOutSlowIn,
                    enlargeCenterPage: true,
                    scrollDirection: Axis.horizontal,
                  ),
                ),
              )
            ]);
          } else if (snapshot.hasError) {
            return Text('${snapshot.error}');
          }
          return Center(child: CircularProgressIndicator());
        });
  }
}
