import 'package:albadael/Constant/api_connection.dart';
import 'package:albadael/Models/About-Us/autogenerated_about-us.dart';
import 'package:carousel_slider/carousel_options.dart';
import 'package:carousel_slider/carousel_slider.dart';
import 'package:flutter/material.dart';

// ignore: camel_case_types
class Section_Bartner extends StatefulWidget {
  const Section_Bartner({Key? key}) : super(key: key);

  @override
  _Section_BartnerState createState() => _Section_BartnerState();
}

// ignore: camel_case_types
class _Section_BartnerState extends State<Section_Bartner> {
  late Future<Autogenerated_team?> datateam;
  @override
  void initState() {
    super.initState();
    datateam = getdatateam();
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<Autogenerated_team?>(
        future: datateam,
        builder: (context, snapshot) {
          if (snapshot.hasData) {
            return Column(children: [
              Padding(
                padding: const EdgeInsets.only(right: 8, left: 8, top: 8),
                child: CarouselSlider.builder(
                  itemCount: snapshot.data!.data.partner.length,
                  itemBuilder:
                      (BuildContext context, int itemIndex, int pageViewIndex) {
                    return Card(
                      elevation: 2,
                      child: Container(
                        decoration: BoxDecoration(
                            color: Colors.white,
                            borderRadius:
                                BorderRadius.all(Radius.circular(15))),
                        width: MediaQuery.of(context).size.width / 1.5,
                        child: Column(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Container(
                                width: 250,
                                height: 150,
                                decoration: BoxDecoration(
                                  image: DecorationImage(
                                    image: getimage(snapshot
                                        .data!.data.partner[itemIndex].cover
                                        .toString()),
                                  ),
                                )),
                            SizedBox(
                              height: 10,
                            ),
                            Text(snapshot.data!.data.partner[itemIndex].name,
                                style: TextStyle(fontWeight: FontWeight.bold)),
                          ],
                        ),
                      ),
                    );
                  },
                  options: CarouselOptions(
                    height: 300,
                    aspectRatio: 16 / 9,
                    viewportFraction: 0.8,
                    initialPage: 0,
                    enableInfiniteScroll: true,
                    reverse: false,
                    autoPlay: true,
                    autoPlayInterval: Duration(seconds: 4),
                    autoPlayAnimationDuration: Duration(milliseconds: 800),
                    autoPlayCurve: Curves.fastOutSlowIn,
                    enlargeCenterPage: true,
                    scrollDirection: Axis.vertical,
                  ),
                ),
              )
            ]);
          } else if (snapshot.hasError) {
            return Text('${snapshot.error}');
          }
          return Center(
              child: Container(
            height: MediaQuery.of(context).size.height / 50,
            width: MediaQuery.of(context).size.width / 4,
          ));
        });
  }
}
