import 'package:albadael/Constant/api_connection.dart';
import 'package:albadael/Models/Home/autogenerated.dart';
import 'package:flutter/material.dart';
import 'package:flutter_html/flutter_html.dart';

// ignore: camel_case_types
class Section_About_us_In_Screen_About_us extends StatefulWidget {
  const Section_About_us_In_Screen_About_us({Key? key}) : super(key: key);

  @override
  _Section_About_us_In_Screen_About_usState createState() =>
      _Section_About_us_In_Screen_About_usState();
}

// ignore: camel_case_types
class _Section_About_us_In_Screen_About_usState
    extends State<Section_About_us_In_Screen_About_us> {
  late Future<Autogenerated> data;

  @override
  void initState() {
    super.initState();
    data = readdata();
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<Autogenerated>(
        future: data,
        builder: (context, snapshot) {
          if (snapshot.hasData) {
            return Column(
              children: [
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Text(
                    snapshot.data!.data.about.title,
                    style: TextStyle(
                        fontWeight: FontWeight.bold,
                        fontSize: 18,
                        color: Color(0xff2c4755)),
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.all(14),
                  child: Text(
                    snapshot.data!.data.about.subject,
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.all(8),
                  child: Html(
                    shrinkWrap: true,
                    data: snapshot.data!.data.about.desc,
                  ),
                ),
              ],
            );
          } else if (snapshot.hasError) {
            return Text('${snapshot.error}');
          }
          return Center(child: CircularProgressIndicator());
        });
  }
}
