import 'package:albadael/Constant/api_connection.dart';
import 'package:albadael/Models/Public_API/autogenerated.dart';
import 'package:albadael/Widget/Drawer/column_in_drawer.dart';
import 'package:flutter/material.dart';

class Wdrawer extends StatefulWidget {
  const Wdrawer({
    Key? key,
  }) : super(key: key);

  @override
  _WdrawerState createState() => _WdrawerState();
}

class _WdrawerState extends State<Wdrawer> {
  late Future<Autogenerated> data;

  @override
  void initState() {
    super.initState();
    data = readdata();
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<Autogenerated>(
      future: data,
      builder: (context, snapshot) {
        if (snapshot.hasData) {
          return Drawer(
            child: Column(
              children: [
                Container(
                  alignment: Alignment.center,
                  height: MediaQuery.of(context).size.height / 4,
                  width: MediaQuery.of(context).size.width,
                  decoration: BoxDecoration(
                      color: Color(0xff2c4755),
                      image: DecorationImage(
                        image: getimage(snapshot.data!.data.general.logo),
                      )),
                ),
                Column_Drawer(),
              ],
            ),
          );
        } else if (snapshot.hasError) {
          return Text('${snapshot.error}');
        }
        return Center(child: CircularProgressIndicator());
      },
    );
  }
}
