import 'dart:ui';
import 'package:albadael/Constant/api_connection.dart';
import 'package:albadael/Models/Home/autogenerated.dart';
import 'package:albadael/Widget/About-Us/section_about_us.dart';
import 'package:albadael/Widget/About-Us/section_faq.dart';
import 'package:albadael/Widget/About-Us/section_team.dart';
import 'package:albadael/Widget/Public/divider_between_section.dart';
import 'package:albadael/Widget/Footer/footer.dart';
import 'package:albadael/Widget/Public/title_name_screen.dart';
import 'package:flutter/material.dart';

class AboutScreen extends StatefulWidget {
  const AboutScreen({Key? key}) : super(key: key);

  @override
  _AboutScreenState createState() => _AboutScreenState();
}

class _AboutScreenState extends State<AboutScreen> {
  late Future<Autogenerated> data;

  @override
  void initState() {
    super.initState();
    data = readdata();
  }

  bool visibile = false;

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<Autogenerated>(
        future: data,
        builder: (context, snapshot) {
          if (snapshot.hasData) {
            return Scaffold(
              appBar: AppBar(
                backgroundColor: Color(0xff2c4755),
                title: Text(snapshot.data!.data.about.title),
              ),
              body: SingleChildScrollView(
                physics: ScrollPhysics(),
                child: Column(children: [
                  Title_name_screen(title: 'About-Us'),
                  Section_About_us_In_Screen_About_us(),
                  Divider_between_section(name: 'Our Team'),
                  Section_Team(),
                  Divider_between_section(name: 'FAQ'),
                  Section_Faq(),
                  Footer()
                ]),
              ),
            );
          } else if (snapshot.hasError) {
            return Text('${snapshot.error}');
          }
          return Center(child: CircularProgressIndicator());
        });
  }
}
