import 'package:albadael/Constant/api_connection.dart';
import 'package:albadael/Models/Home/autogenerated.dart';
import 'package:albadael/Widget/About-Us/section_team.dart';
import 'package:albadael/Widget/Drawer/drawer.dart';
import 'package:albadael/Widget/HomePage/banner.dart';
import 'package:albadael/Widget/HomePage/section_blog.dart';
import 'package:albadael/Widget/HomePage/section_services.dart';
import 'package:albadael/Widget/HomePage/section_about_us.dart';
import 'package:albadael/Widget/Public/appbar_homepage.dart';
import 'package:albadael/Widget/Public/divider_between_section.dart';
import 'package:albadael/Widget/Public/fab_message.dart';
import 'package:albadael/Widget/Public/title_name_screen.dart';
import 'package:flutter/material.dart';

class Home extends StatefulWidget {
  const Home({Key? key}) : super(key: key);

  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  late Future<Autogenerated?> apiCall;

  @override
  void initState() {
    super.initState();
    apiCall = getdatapublic();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBarHomePage(),
      drawer: Wdrawer(),
      body: SingleChildScrollView(
        child: Column(children: [
          Title_name_screen(
            title: 'Home Page',
          ),
          banner_in_homepage(),
          Divider_between_section(
            name: 'About Us',
          ),
          Section_about_us(),
          Divider_between_section(
            name: 'Services',
          ),
          Section_Services(),
          Divider_between_section(
            name: 'Our Team',
          ),
          Section_Team(),
          Divider_between_section(
            name: 'Blog',
          ),
          Section_Blog(),
          SizedBox(
            height: MediaQuery.of(context).size.height / 12,
          )
        ]),
      ),
      floatingActionButton: ButtonContactUs(),
    );
  }
}
