import 'package:albadael/Constant/api_connection.dart';
import 'package:albadael/Models/Home/autogenerated.dart';
import 'package:albadael/Widget/HomePage/section_protfolio.dart';
import 'package:albadael/Widget/Public/appbarwidget.dart';
import 'package:albadael/Widget/Public/fab_message.dart';
import 'package:flutter/material.dart';

class Protfolio extends StatefulWidget {
  const Protfolio({Key? key}) : super(key: key);

  @override
  _ProtfolioState createState() => _ProtfolioState();
}

class _ProtfolioState extends State<Protfolio> {
  late Future<Autogenerated?> apiCall;

  @override
  void initState() {
    super.initState();
    // data = readdata();
    apiCall = getdatapublic();
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<Autogenerated?>(
        future: apiCall,
        builder: (context, snapshot) {
          if (snapshot.hasData) {
            return Scaffold(
              appBar: AppBarWidget(),
              // appBar: AppBar(
              //   iconTheme: IconThemeData(
              //     color: Colors.grey[600],
              //   ),
              //   backgroundColor: Colors.white,
              //   elevation: 0,
              //   title: Padding(
              //     padding: EdgeInsets.only(
              //         right: MediaQuery.of(context).size.width / 5),
              //     child: Container(
              //       alignment: Alignment.center,
              //       width: MediaQuery.of(context).size.width / 1.5,
              //       child: Row(
              //           mainAxisAlignment: MainAxisAlignment.center,
              //           children: [
              //             Container(
              //                 height: MediaQuery.of(context).size.height / 14,
              //                 width: MediaQuery.of(context).size.width / 6,
              //                 child: Image.asset('assets/images/logo.png')),
              //             Text(
              //               snapshot.data!.data.about.title,
              //               style: TextStyle(color: Colors.black),
              //             ),
              //           ]),
              //     ),
              //   ),
              // ),
              body: Section_Protfolio(),
              //  SingleChildScrollView(
              //     physics: ScrollPhysics(),
              //     child: Column(children: [
              //       Title_name_screen(title: 'Protfolio'),
              //       Padding(
              //         padding: const EdgeInsets.all(8.0),
              //         child: new ListView.builder(
              //             physics: NeverScrollableScrollPhysics(),
              //             primary: false,
              //             shrinkWrap: true,
              //             itemCount: snapshot.data!.data.pcategories.length,
              //             itemBuilder: (context, index) {
              //               return Card(
              //                 margin: EdgeInsets.all(5),
              //                 child: ListTile(
              //                   title: Text(
              //                     snapshot.data!.data.pcategories[index].name,
              //                     style: TextStyle(color: Color(0xff2c4755)),
              //                   ),
              //                 ),
              //               );
              //             }),
              //       ),
              //       Padding(
              //         padding: const EdgeInsets.all(8.0),
              //         child: new ListView.builder(
              //             physics: NeverScrollableScrollPhysics(),
              //             primary: false,
              //             shrinkWrap: true,
              //             itemCount: snapshot.data!.data.portfolio.length,
              //             itemBuilder: (context, index) {
              //               return Column(
              //                 children: [
              //                   Container(
              //                     height: 250,
              //                     width: MediaQuery.of(context).size.width,
              //                     decoration: BoxDecoration(
              //                         color: Colors.grey[200],
              //                         borderRadius:
              //                             BorderRadius.all(Radius.circular(5)),
              //                         image: DecorationImage(
              //                             fit: BoxFit.fitWidth,
              //                             image: getimage(snapshot.data!.data
              //                                 .portfolio[index].cover))),
              //                   ),
              //                   SizedBox(
              //                     height: 10,
              //                   ),
              //                   Text(
              //                     snapshot.data!.data.portfolio[index].name,
              //                     style: TextStyle(
              //                         color: Color(0xff2c4755),
              //                         fontWeight: FontWeight.bold),
              //                   ),
              //                   SizedBox(
              //                     height: 10,
              //                   ),
              //                   Html(
              //                       data: snapshot
              //                           .data!.data.portfolio[index].desc),
              //                   Divider(
              //                     thickness: 1,
              //                     height: 20,
              //                   )
              //                 ],
              //               );
              //             }),
              //       ),
              //     ])),
              floatingActionButton: ButtonContactUs(),
            );
          } else if (snapshot.hasError) {
            return Text('${snapshot.error}');
          }
          return Center(child: CircularProgressIndicator());
        });
  }
}
