import 'package:albadael/Constant/api_connection.dart';
import 'package:albadael/Models/Home/autogenerated.dart';
import 'package:albadael/Widget/HomePage/section_protfolio.dart';
import 'package:albadael/Widget/Public/appbarwidget.dart';
import 'package:albadael/Widget/Public/fab_message.dart';
import 'package:flutter/material.dart';

class Protfolio extends StatefulWidget {
  const Protfolio({Key? key}) : super(key: key);

  @override
  _ProtfolioState createState() => _ProtfolioState();
}

class _ProtfolioState extends State<Protfolio> {
  late Future<Autogenerated?> apiCall;

  @override
  void initState() {
    super.initState();
    apiCall = getdatapublic();
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<Autogenerated?>(
        future: apiCall,
        builder: (context, snapshot) {
          if (snapshot.hasData) {
            return Scaffold(
              appBar: AppBarWidget(),
              body: Section_Protfolio(),
              floatingActionButton: ButtonContactUs(),
            );
          } else if (snapshot.hasError) {
            return Text('${snapshot.error}');
          }
          return Center(child: CircularProgressIndicator());
        });
  }
}
