import 'package:albadael/Constant/api_connection.dart';
import 'package:albadael/Models/Public_API/autogenerated.dart';
import 'package:albadael/Widget/Footer/footer.dart';
import 'package:albadael/Widget/Public/title_name_screen.dart';
import 'package:flutter/material.dart';
import 'package:flutter_html/flutter_html.dart';

class Protfolio extends StatefulWidget {
  const Protfolio({Key? key}) : super(key: key);

  @override
  _ProtfolioState createState() => _ProtfolioState();
}

class _ProtfolioState extends State<Protfolio> {
  late Future<Autogenerated> data;

  @override
  void initState() {
    super.initState();
    data = readdata();
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<Autogenerated>(
        future: data,
        builder: (context, snapshot) {
          if (snapshot.hasData) {
            return Scaffold(
              appBar: AppBar(
                backgroundColor: Color(0xff2c4755),
                title: Text(snapshot.data!.data.about.title),
              ),
              body: SingleChildScrollView(
                  physics: ScrollPhysics(),
                  child: Column(children: [
                    Title_name_screen(title: 'Protfolio'),
                    Padding(
                      padding: const EdgeInsets.all(8.0),
                      child: new ListView.builder(
                          physics: NeverScrollableScrollPhysics(),
                          primary: false,
                          shrinkWrap: true,
                          itemCount: snapshot.data!.data.pcategories.length,
                          itemBuilder: (context, index) {
                            return Card(
                              margin: EdgeInsets.all(5),
                              child: ListTile(
                                title: Text(
                                  snapshot.data!.data.pcategories[index].name,
                                  style: TextStyle(color: Color(0xff2c4755)),
                                ),
                              ),
                            );
                          }),
                    ),
                    Padding(
                      padding: const EdgeInsets.all(8.0),
                      child: new ListView.builder(
                          physics: NeverScrollableScrollPhysics(),
                          primary: false,
                          shrinkWrap: true,
                          itemCount: snapshot.data!.data.portfolio.length,
                          itemBuilder: (context, index) {
                            return Column(
                              children: [
                                Container(
                                  height: 250,
                                  width: MediaQuery.of(context).size.width,
                                  decoration: BoxDecoration(
                                      color: Colors.grey[200],
                                      borderRadius:
                                          BorderRadius.all(Radius.circular(5)),
                                      image: DecorationImage(
                                          fit: BoxFit.fitWidth,
                                          image: getimage(snapshot.data!.data
                                              .portfolio[index].cover))),
                                ),
                                SizedBox(
                                  height: 10,
                                ),
                                Text(
                                  snapshot.data!.data.portfolio[index].name,
                                  style: TextStyle(
                                      color: Color(0xff2c4755),
                                      fontWeight: FontWeight.bold),
                                ),
                                SizedBox(
                                  height: 10,
                                ),
                                Html(
                                    data: snapshot
                                        .data!.data.portfolio[index].desc),
                                Divider(
                                  thickness: 1,
                                  height: 20,
                                )
                              ],
                            );
                          }),
                    ),
                    Footer()
                  ])),
            );
          } else if (snapshot.hasError) {
            return Text('${snapshot.error}');
          }
          return Center(child: CircularProgressIndicator());
        });
  }
}
