import 'package:albadael/Constant/api_connection.dart';
import 'package:albadael/Models/Home/autogenerated.dart';
import 'package:albadael/Widget/Public/fab_message.dart';
import 'package:albadael/Widget/Public/title_name_screen.dart';
import 'package:flutter/material.dart';

class Srevices extends StatefulWidget {
  const Srevices({Key? key}) : super(key: key);

  @override
  _SrevicesState createState() => _SrevicesState();
}

class _SrevicesState extends State<Srevices> {
  late Future<Autogenerated?> apiCall;

  @override
  void initState() {
    super.initState();
    // data = readdata();
    apiCall = getdatapublic();
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<Autogenerated?>(
        future: apiCall,
        builder: (context, snapshot) {
          if (snapshot.hasData) {
            return Scaffold(
              appBar: AppBar(
                iconTheme: IconThemeData(
                  color: Colors.grey[600],
                ),
                backgroundColor: Colors.white,
                elevation: 0,
                title: Padding(
                  padding: EdgeInsets.only(
                      right: MediaQuery.of(context).size.width / 5),
                  child: Container(
                    alignment: Alignment.center,
                    width: MediaQuery.of(context).size.width / 1.5,
                    child: Row(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Container(
                              height: MediaQuery.of(context).size.height / 14,
                              width: MediaQuery.of(context).size.width / 6,
                              child: Image.asset('assets/images/logo.png')),
                          Text(
                            snapshot.data!.data.about.title,
                            style: TextStyle(color: Colors.black),
                          ),
                        ]),
                  ),
                ),
              ),
              body: SingleChildScrollView(
                physics: ScrollPhysics(),
                child: Column(children: [
                  Title_name_screen(title: "Services"),
                  Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: new ListView.builder(
                        physics: NeverScrollableScrollPhysics(),
                        primary: false,
                        shrinkWrap: true,
                        itemCount: snapshot.data!.data.service.length,
                        itemBuilder: (context, index) {
                          return Column(children: [
                            Container(
                                alignment: Alignment.center,
                                width: MediaQuery.of(context).size.width / 1.5,
                                height: MediaQuery.of(context).size.height / 5,
                                decoration: BoxDecoration(
                                  image: DecorationImage(
                                      image: getimage(snapshot
                                          .data!.data.service[index].icon
                                          .toString()),
                                      fit: BoxFit.fill),
                                )),
                            SizedBox(
                              height: 10,
                            ),
                            Text(
                              snapshot.data!.data.service[index].title,
                              style: TextStyle(
                                  color: Color(0xff2c4755),
                                  fontWeight: FontWeight.bold),
                            ),
                            SizedBox(
                              height: 10,
                            ),
                            Text(
                              snapshot.data!.data.service[index].quote,
                              softWrap: true,
                              style: TextStyle(
                                color: Color(0xff1abc9c),
                              ),
                            ),
                            Text(snapshot.data!.data.service[index].desc),
                            SizedBox(
                              height: 25,
                            ),
                          ]);
                        }),
                  ),
                ]),
              ),
              floatingActionButton: ButtonContactUs(),
            );
          } else if (snapshot.hasError) {
            return Text('${snapshot.error}');
          }
          return Center(
              child: Container(
            height: MediaQuery.of(context).size.height / 50,
            width: MediaQuery.of(context).size.width / 4,
          ));
        });
  }
}
