import 'package:albadael/Constant/api_connection.dart';
import 'package:albadael/Models/Home/autogenerated.dart';
import 'package:albadael/Widget/Public/appbarwidget.dart';
import 'package:albadael/Widget/Public/fab_message.dart';
import 'package:albadael/Widget/Public/title_name_screen.dart';
import 'package:flutter/material.dart';

class Srevices extends StatefulWidget {
  const Srevices({Key? key}) : super(key: key);

  @override
  _SrevicesState createState() => _SrevicesState();
}

class _SrevicesState extends State<Srevices> {
  late Future<Autogenerated?> apiCall;

  @override
  void initState() {
    super.initState();
    apiCall = getdatapublic();
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<Autogenerated?>(
        future: apiCall,
        builder: (context, snapshot) {
          if (snapshot.hasData) {
            return Scaffold(
              appBar: AppBarWidget(),
              body: SingleChildScrollView(
                physics: ScrollPhysics(),
                child: Column(children: [
                  Title_name_screen(title: "Services"),
                  new ListView.builder(
                      physics: NeverScrollableScrollPhysics(),
                      primary: false,
                      shrinkWrap: true,
                      itemCount: snapshot.data!.data.service.length,
                      itemBuilder: (context, index) {
                        return Padding(
                          padding: const EdgeInsets.all(8.0),
                          child: Container(
                            decoration: BoxDecoration(
                                color: Colors.grey[100],
                                borderRadius:
                                    BorderRadius.all(Radius.circular(12))),
                            child: ListTile(
                              leading: Container(
                                  alignment: Alignment.center,
                                  width: 35,
                                  height: 35,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                        image: getimage(snapshot
                                            .data!.data.service[index].icon
                                            .toString()),
                                        fit: BoxFit.fill),
                                  )),
                              title: Text(
                                snapshot.data!.data.service[index].title,
                                style: TextStyle(
                                    color: Color(0xff2c4755),
                                    fontWeight: FontWeight.bold),
                              ),
                              subtitle: Text(
                                snapshot.data!.data.service[index].quote,
                                softWrap: true,
                                style: TextStyle(
                                  color: Color(0xff1abc9c),
                                ),
                              ),
                            ),
                          ),
                        );
                      }),
                ]),
              ),
              floatingActionButton: ButtonContactUs(),
            );
          } else if (snapshot.hasError) {
            return Text('${snapshot.error}');
          }
          return Center(
              child: Container(
            height: MediaQuery.of(context).size.height / 50,
            width: MediaQuery.of(context).size.width / 4,
          ));
        });
  }
}
