class Autogenerated_team {
  late String status;
  late String statusCode;
  late Null error;
  late Data data;

  Autogenerated_team(
      {required this.status,
      required this.statusCode,
      required this.error,
      required this.data});

  Autogenerated_team.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    statusCode = json['statusCode'];
    error = json['error'];
    data = json['data'] = Data.fromJson(json['data']);
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    data['statusCode'] = this.statusCode;
    data['error'] = this.error;
    if (this.data != null) {
      data['data'] = this.data.toJson();
    }
    return data;
  }
}

class Data {
  late List<Team> team;
  late List<Faq> faq;

  Data({required this.team});

  Data.fromJson(Map<String, dynamic> json) {
    if (json['team'] != null) {
      team = <Team>[];
      json['team'].forEach((v) {
        team.add(new Team.fromJson(v));
      });
    }
    if (json['faq'] != null) {
      faq = <Faq>[];
      json['faq'].forEach((v) {
        faq.add(new Faq.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();

    if (this.team != null) {
      data['team'] = this.team.map((v) => v.toJson()).toList();
    }
    if (this.faq != null) {
      data['faq'] = this.faq.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Team {
  late int id;
  late String name;
  late String position;
  late String photo;
  late Null facebook;
  late Null twitter;
  late Null instagram;
  late Null linkedin;
  late String createdAt;
  late String updatedAt;

  Team(
      {required this.id,
      required this.name,
      required this.position,
      required this.photo,
      required this.facebook,
      required this.twitter,
      required this.instagram,
      required this.linkedin,
      required this.createdAt,
      required this.updatedAt});

  Team.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    position = json['position'];
    photo = json['photo'];
    facebook = json['facebook'];
    twitter = json['twitter'];
    instagram = json['instagram'];
    linkedin = json['linkedin'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['position'] = this.position;
    data['photo'] = this.photo;
    data['facebook'] = this.facebook;
    data['twitter'] = this.twitter;
    data['instagram'] = this.instagram;
    data['linkedin'] = this.linkedin;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    return data;
  }
}

class Faq {
  late int id;
  late String question;
  late String answer;
  late String createdAt;
  late String updatedAt;

  Faq(
      {required this.id,
      required this.question,
      required this.answer,
      required this.createdAt,
      required this.updatedAt});

  Faq.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    question = json['question'];
    answer = json['answer'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['question'] = this.question;
    data['answer'] = this.answer;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    return data;
  }
}
