import 'package:albadael/Constant/api_connection.dart';
import 'package:albadael/Models/Home/autogenerated.dart';
import 'package:albadael/Widget/Footer/row_social_media.dart';
import 'package:albadael/Widget/Footer/space.dart';
import 'package:albadael/Widget/Footer/text.dart';
import 'package:flutter/material.dart';

class Footer extends StatefulWidget {
  const Footer({
    Key? key,
  }) : super(key: key);

  @override
  _FooterState createState() => _FooterState();
}

class _FooterState extends State<Footer> {
  late Future<Autogenerated> data;

  @override
  void initState() {
    super.initState();
    data = readdata();
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<Autogenerated>(
        future: data,
        builder: (context, snapshot) {
          if (snapshot.hasData) {
            return Padding(
              padding: const EdgeInsets.only(top: 10),
              child: Container(
                  color: Color(0xff2c4755),
                  alignment: Alignment.center,
                  height: MediaQuery.of(context).size.height / 4,
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      text_footer(title: snapshot.data!.data.general.address1),
                      space(),
                      text_footer(title: snapshot.data!.data.general.address2),
                      space(),
                      text_footer(title: snapshot.data!.data.general.phone),
                      space(),
                      text_footer(title: snapshot.data!.data.general.email),
                      SizedBox(
                        height: MediaQuery.of(context).size.height / 50,
                      ),
                      social_media_in_footer(),
                    ],
                  )),
            );
          } else if (snapshot.hasError) {
            return Text('${snapshot.error}');
          }
          return Center(child: CircularProgressIndicator());
        });
  }
}
