import 'package:albadael/Constant/api_connection.dart';
import 'package:albadael/Models/Public_API/autogenerated.dart';
import 'package:carousel_slider/carousel_slider.dart';
import 'package:flutter/material.dart';

// ignore: camel_case_types
class banner_in_homepage extends StatefulWidget {
  const banner_in_homepage({
    Key? key,
  }) : super(key: key);

  @override
  _banner_in_homepageState createState() => _banner_in_homepageState();
}

// ignore: camel_case_types
class _banner_in_homepageState extends State<banner_in_homepage> {
  late Future<Autogenerated> data;

  @override
  void initState() {
    super.initState();
    data = readdata();
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<Autogenerated>(
      future: data,
      builder: (context, snapshot) {
        if (snapshot.hasData) {
          return Container(
              height: MediaQuery.of(context).size.height / 2.9,
              width: MediaQuery.of(context).size.width,
              child: CarouselSlider.builder(
                itemCount: snapshot.data!.data.banner.length,
                itemBuilder:
                    (BuildContext context, int itemIndex, int pageViewIndex) {
                  return Container(
                    decoration: BoxDecoration(
                        image: DecorationImage(
                            image: getimage(
                                snapshot.data!.data.banner[itemIndex].cover),
                            fit: BoxFit.cover)),
                    width: MediaQuery.of(context).size.width,
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Container(
                          alignment: Alignment.center,
                          height: 50,
                          width: 200,
                          decoration: BoxDecoration(
                              color: Color(0xFF6a8e95).withOpacity(0.5),
                              borderRadius:
                                  BorderRadius.all(Radius.circular(5))),
                          child: Text(
                              snapshot.data!.data.banner[itemIndex].title,
                              style: TextStyle(
                                  fontWeight: FontWeight.bold,
                                  color: Colors.white)),
                        ),
                      ],
                    ),
                  );
                },
                options: CarouselOptions(
                  height: 400,
                  aspectRatio: 16 / 9,
                  viewportFraction: 1,
                  initialPage: 0,
                  enableInfiniteScroll: true,
                  reverse: false,
                  autoPlay: true,
                  autoPlayInterval: Duration(seconds: 4),
                  autoPlayAnimationDuration: Duration(milliseconds: 800),
                  autoPlayCurve: Curves.fastOutSlowIn,
                  enlargeCenterPage: true,
                  scrollDirection: Axis.horizontal,
                ),
              ));
        } else if (snapshot.hasError) {
          return Text('${snapshot.error}');
        }
        return Center(child: CircularProgressIndicator());
      },
    );
  }
}
