import 'package:albadael/Constant/api_connection.dart';
import 'package:albadael/Models/Home/autogenerated.dart';
import 'package:albadael/Screens/about.dart';
import 'package:flutter/material.dart';

// ignore: camel_case_types
class Section_about_us extends StatefulWidget {
  const Section_about_us({Key? key}) : super(key: key);

  @override
  _Section_about_usState createState() => _Section_about_usState();
}

// ignore: camel_case_types
class _Section_about_usState extends State<Section_about_us> {
  late Future<Autogenerated?> apiCall;

  @override
  void initState() {
    super.initState();
    // data = readdata();
    apiCall = getdatapublic();
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<Autogenerated?>(
      future: apiCall,
      builder: (BuildContext context, AsyncSnapshot<Autogenerated?> snapshot) {
        if (snapshot.hasData) {
          return Column(
            // ignore: always_specify_types
            children: [
              Padding(
                padding: const EdgeInsets.all(8.0),
                child: Text(
                  snapshot.data!.data.about.title,
                  style: const TextStyle(
                      fontWeight: FontWeight.bold, fontSize: 16),
                ),
              ),
              Padding(
                padding: const EdgeInsets.only(left: 10, top: 10, bottom: 10),
                child: Text(
                  snapshot.data!.data.about.subject,
                  softWrap: true,
                ),
              ),
              ElevatedButton(
                style: ElevatedButton.styleFrom(
                  primary: const Color(0xff1daad2),
                  // Color(0xff1abc9c)
                ),
                // ignore: sort_child_properties_last
                child: const Text('Learn more'),
                // child: const Text('Learn more'),
                onPressed: () => Navigator.push(
                  context,
                  MaterialPageRoute<void>(
                      builder: (BuildContext context) => const AboutScreen()),
                ),
              ),
            ],
          );
        } else if (snapshot.hasError) {
          return Text('${snapshot.error}');
        }
        return Center(
            child: Container(
          height: MediaQuery.of(context).size.height / 50,
          width: MediaQuery.of(context).size.width / 4,
        ));
      },
    );
  }
}
