import 'package:albadael/Constant/api_connection.dart';
import 'package:albadael/Models/Home/autogenerated.dart';
import 'package:flutter/material.dart';

// ignore: camel_case_types
class Section_Services extends StatefulWidget {
  const Section_Services({
    Key? key,
  }) : super(key: key);

  @override
  _Section_ServicesState createState() => _Section_ServicesState();
}

// ignore: camel_case_types
class _Section_ServicesState extends State<Section_Services> {
  late Future<Autogenerated?> apiCall;

  @override
  void initState() {
    super.initState();
    apiCall = getdatapublic();
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<Autogenerated?>(
      future: apiCall,
      builder: (context, snapshot) {
        if (snapshot.hasData) {
          return Padding(
            padding: const EdgeInsets.all(8.0),
            child: new GridView.builder(
                gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                    crossAxisCount: 2),
                physics: NeverScrollableScrollPhysics(),
                primary: false,
                shrinkWrap: true,
                itemCount: snapshot.data!.data.service.length,
                itemBuilder: (context, index) {
                  return Card(
                    elevation: 4,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                    margin: EdgeInsets.all(8.0),
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Container(
                          height: 45,
                          width: 45,
                          decoration: BoxDecoration(
                              image: DecorationImage(
                            image: getimage(snapshot
                                .data!.data.service[index].icon
                                .toString()),
                          )),
                        ),
                        Padding(
                          padding: EdgeInsets.only(
                              top: MediaQuery.of(context).size.height / 30),
                          child: Text(
                            snapshot.data!.data.service[index].title,
                            style: TextStyle(color: Color(0xff2c4755)),
                          ),
                        ),
                      ],
                    ),
                  );
                }),
          );
        } else if (snapshot.hasError) {
          return Text('${snapshot.error}');
        }
        return Center(
            child: Container(
          height: MediaQuery.of(context).size.height / 50,
          width: MediaQuery.of(context).size.width / 4,
        ));
      },
    );
  }
}
