import 'package:albadael/Constant/api_connection.dart';
import 'package:albadael/Models/Public_API/autogenerated.dart';
import 'package:albadael/Screens/About.dart';
import 'package:flutter/material.dart';

// ignore: camel_case_types
class Section_about_us extends StatefulWidget {
  const Section_about_us({Key? key}) : super(key: key);

  @override
  _Section_about_usState createState() => _Section_about_usState();
}

// ignore: camel_case_types
class _Section_about_usState extends State<Section_about_us> {
  late Future<Autogenerated> data;

  @override
  void initState() {
    super.initState();
    data = readdata();
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<Autogenerated>(
      future: data,
      builder: (context, snapshot) {
        if (snapshot.hasData) {
          return Column(
            children: [
              Padding(
                padding: const EdgeInsets.all(8.0),
                child: Text(
                  snapshot.data!.data.about.title,
                  style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
                ),
              ),
              Padding(
                padding: const EdgeInsets.only(left: 10, top: 10, bottom: 10),
                child: Text(
                  snapshot.data!.data.about.subject,
                  softWrap: true,
                ),
              ),
              ElevatedButton(
                style: ElevatedButton.styleFrom(primary: Color(0xff1abc9c)),
                child: Text('Learn more'),
                onPressed: () => Navigator.of(context).push(
                    MaterialPageRoute(builder: (context) => AboutScreen())),
              ),
            ],
          );
        } else if (snapshot.hasError) {
          return Text('${snapshot.error}');
        }
        return Center(child: CircularProgressIndicator());
      },
    );
  }
}
