import 'package:albadael/Constant/api_connection.dart';
import 'package:albadael/Models/Home/autogenerated.dart';
import 'package:flutter/material.dart';
import 'package:scrollable_list_tabview/scrollable_list_tabview.dart';

// ignore: camel_case_types
class Section_Protfolio extends StatefulWidget {
  const Section_Protfolio({
    Key? key,
  }) : super(key: key);

  @override
  _Section_ProtfolioState createState() => _Section_ProtfolioState();
}

// ignore: camel_case_types
class _Section_ProtfolioState extends State<Section_Protfolio> {
  late Future<Autogenerated?> apiCall;

  List getCategory(
    List data,
    String name,
  ) {
    List subgategoray = [];
    for (var a in data)
      if (data.contains(a.name == 1)) subgategoray.add(a.name == 1);

    return subgategoray;
  }

  @override
  void initState() {
    super.initState();
    apiCall = getdatapublic();
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<Autogenerated?>(
      future: apiCall,
      builder: (context, snapshot) {
        if (snapshot.hasData) {
          return Padding(
              padding: const EdgeInsets.all(8.0),
              child: ScrollableListTabView(
                  tabHeight: 48,
                  bodyAnimationDuration: const Duration(milliseconds: 150),
                  tabAnimationCurve: Curves.easeOut,
                  tabAnimationDuration: const Duration(milliseconds: 200),
                  tabs: [
                    ScrollableListTab(
                      tab: ListTab(
                          label: Text('All'),
                          // icon: Icon(Icons.group),
                          showIconOnList: false),
                      body: ListView.builder(
                          physics: NeverScrollableScrollPhysics(),
                          primary: false,
                          shrinkWrap: true,
                          itemCount: snapshot.data!.data.portfolio.length,
                          itemBuilder: (context, index) {
                            return Column(
                              children: [
                                Container(
                                  height: 250,
                                  width: MediaQuery.of(context).size.width,
                                  decoration: BoxDecoration(
                                      color: Colors.grey[200],
                                      borderRadius:
                                          BorderRadius.all(Radius.circular(5)),
                                      image: DecorationImage(
                                          fit: BoxFit.fitWidth,
                                          image: getimage(snapshot.data!.data
                                              .portfolio[index].cover))),
                                ),
                                SizedBox(
                                  height: 10,
                                ),
                                Text(
                                  snapshot.data!.data.portfolio[index].name
                                      .toString(),
                                  style: TextStyle(
                                      color: Color(0xff2c4755),
                                      fontWeight: FontWeight.bold),
                                ),
                                SizedBox(
                                  height: 10,
                                ),
                                Text(snapshot.data!.data.portfolio[index].desc),
                                Divider(
                                  thickness: 1,
                                  height: 20,
                                )
                              ],
                            );
                          }),
                    ),
                    ScrollableListTab(
                      tab: ListTab(
                          label: Text('Marketing'), showIconOnList: false),
                      body: ListView.builder(
                          physics: NeverScrollableScrollPhysics(),
                          primary: false,
                          shrinkWrap: true,
                          itemCount: getCategory(
                                  snapshot.data!.data.portfolio, 'pcategory_id')
                              .length,
                          itemBuilder: (context, index) {
                            return Column(
                              children: [
                                Container(
                                  height: 250,
                                  width: MediaQuery.of(context).size.width,
                                  decoration: BoxDecoration(
                                      color: Colors.grey[200],
                                      borderRadius:
                                          BorderRadius.all(Radius.circular(5)),
                                      image: DecorationImage(
                                          fit: BoxFit.fitWidth,
                                          image: getimage(snapshot.data!.data
                                              .portfolio[index].cover))),
                                ),
                                SizedBox(
                                  height: 10,
                                ),
                                Text(
                                  snapshot.data!.data.portfolio[index].name,
                                  style: TextStyle(
                                      color: Color(0xff2c4755),
                                      fontWeight: FontWeight.bold),
                                ),
                                SizedBox(
                                  height: 10,
                                ),
                                Text(snapshot.data!.data.portfolio[index].desc),
                                Divider(
                                  thickness: 1,
                                  height: 20,
                                )
                              ],
                            );
                          }),
                    ),
                    ScrollableListTab(
                      tab: ListTab(
                          label: Text('Graphic Design'),
                          // icon: Icon(Icons.group),
                          showIconOnList: false),
                      body: ListView.builder(
                          physics: NeverScrollableScrollPhysics(),
                          primary: false,
                          shrinkWrap: true,
                          itemCount: snapshot.data!.data.portfolio.length,
                          itemBuilder: (context, index) {
                            return Column(
                              children: [
                                Container(
                                  height: 250,
                                  width: MediaQuery.of(context).size.width,
                                  decoration: BoxDecoration(
                                      color: Colors.grey[200],
                                      borderRadius:
                                          BorderRadius.all(Radius.circular(5)),
                                      image: DecorationImage(
                                          fit: BoxFit.fitWidth,
                                          image: getimage(snapshot.data!.data
                                              .portfolio[index].cover))),
                                ),
                                SizedBox(
                                  height: 10,
                                ),
                                Text(
                                  snapshot.data!.data.portfolio[index].name,
                                  style: TextStyle(
                                      color: Color(0xff2c4755),
                                      fontWeight: FontWeight.bold),
                                ),
                                Divider(
                                  thickness: 1,
                                  height: 20,
                                )
                              ],
                            );
                          }),
                    ),
                  ]));
        } else if (snapshot.hasError) {
          return Text('${snapshot.error}');
        }
        return Center(
            child: Container(
          height: MediaQuery.of(context).size.height / 50,
          width: MediaQuery.of(context).size.width / 4,
        ));
      },
    );
  }
}
