import 'package:albadael/Constant/api_connection.dart';
import 'package:albadael/Models/Home/autogenerated.dart';
import 'package:flutter/material.dart';

// ignore: camel_case_types
class Section_Services extends StatefulWidget {
  const Section_Services({
    Key? key,
  }) : super(key: key);

  @override
  _Section_ServicesState createState() => _Section_ServicesState();
}

// ignore: camel_case_types
class _Section_ServicesState extends State<Section_Services> {
  late Future<Autogenerated?> apiCall;

  @override
  void initState() {
    super.initState();
    // data = readdata();
    apiCall = getdatapublic();
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<Autogenerated?>(
      future: apiCall,
      builder: (context, snapshot) {
        if (snapshot.hasData) {
          return Padding(
            padding: const EdgeInsets.all(8.0),
            child: new ListView.builder(
                physics: NeverScrollableScrollPhysics(),
                primary: false,
                shrinkWrap: true,
                itemCount: snapshot.data!.data.service.length,
                itemBuilder: (context, index) {
                  return Card(
                    margin: EdgeInsets.all(5),
                    child: ListTile(
                      leading: Icon(
                        snapshot.data!.data.service[index].id == 5
                            ? Icons.laptop
                            : snapshot.data!.data.service[index].id == 2
                                ? Icons.design_services
                                : snapshot.data!.data.service[index].id == 3
                                    ? Icons.web
                                    : snapshot.data!.data.service[index].id == 4
                                        ? Icons.mobile_friendly
                                        : snapshot.data!.data.service[index]
                                                    .id ==
                                                1
                                            ? Icons.image
                                            : snapshot.data!.data.service[index]
                                                        .id ==
                                                    6
                                                ? Icons.mobile_friendly
                                                : Icons.app_blocking,
                        color: Color(0xff1abc9c),
                      ),
                      title: Text(
                        snapshot.data!.data.service[index].title,
                        style: TextStyle(color: Color(0xff2c4755)),
                      ),
                      // subtitle:
                      //     Text(snapshot.data!.data.service[index].quote),
                    ),
                  );
                }),
          );
        } else if (snapshot.hasError) {
          return Text('${snapshot.error}');
        }
        return Center(child: CircularProgressIndicator());
      },
    );
  }
}
