import 'package:albadael/Constant/api_connection.dart';
import 'package:albadael/Models/Home/autogenerated.dart';
import 'package:flutter/material.dart';

// ignore: camel_case_types
class Section_Blog extends StatefulWidget {
  const Section_Blog({Key? key}) : super(key: key);

  @override
  _Section_BlogState createState() => _Section_BlogState();
}

// ignore: camel_case_types
class _Section_BlogState extends State<Section_Blog> {
  late Future<Autogenerated?> apiCall;

  @override
  void initState() {
    super.initState();
    apiCall = getdatapublic();
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<Autogenerated?>(
        future: apiCall,
        builder: (context, snapshot) {
          if (snapshot.hasData) {
            return Padding(
              padding:
                  const EdgeInsets.only(right: 8, left: 8, top: 15, bottom: 15),
              child: ListView.builder(
                  physics: NeverScrollableScrollPhysics(),
                  primary: false,
                  shrinkWrap: true,
                  itemCount: snapshot.data!.data.post.length,
                  itemBuilder: (context, index) {
                    return Card(
                      elevation: 4,
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(12),
                      ),
                      child: Row(
                        children: [
                          Container(
                            width: MediaQuery.of(context).size.width / 3,
                            height: MediaQuery.of(context).size.height / 5,
                            decoration: BoxDecoration(
                                borderRadius: BorderRadius.only(
                                    topLeft: Radius.circular(12),
                                    bottomLeft: Radius.circular(12)),
                                color: Colors.grey[200],
                                image: DecorationImage(
                                    image: getimage(snapshot
                                        .data!.data.post[index].cover
                                        .toString()))),
                          ),
                          Padding(
                            padding: const EdgeInsets.only(left: 15),
                            child: Column(
                              children: [
                                Text(
                                  snapshot.data!.data.post[index].title,
                                  style: TextStyle(fontWeight: FontWeight.bold),
                                ),
                                SizedBox(
                                  height: 10,
                                ),
                                Text('Read more ...')
                              ],
                            ),
                          )
                        ],
                      ),
                    );
                  }),
            );
          } else if (snapshot.hasError) {
            return Text('${snapshot.error}');
          }
          return Center(
              child: Container(
            height: MediaQuery.of(context).size.height / 50,
            width: MediaQuery.of(context).size.width / 4,
          ));
        });
  }
}
