import 'data_about-us.dart';

class Autogenerated_team {
  late String status;
  late String statusCode;
  late String? error;
  late Data data;

  Autogenerated_team(
      {required this.status,
      required this.statusCode,
      required this.error,
      required this.data});

  Autogenerated_team.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    statusCode = json['statusCode'];
    error = json['error'];
    data = json['data'] = Data.fromJson(json['data']);
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    data['statusCode'] = this.statusCode;
    data['error'] = this.error;
    if (this.data != null) {
      data['data'] = this.data.toJson();
    }
    return data;
  }
}
