import 'data_about-us.dart';

class Autogenerated_team {
  String status;
  String stateNum;
  String? error;
  Data data;

  Autogenerated_team(
      {required this.status,
      required this.stateNum,
      required this.error,
      required this.data});

  factory Autogenerated_team.fromJson(Map<String, dynamic> json) {
    return Autogenerated_team(
        status: json['status'],
        stateNum: json['stateNum'],
        error: json['error'],
        data: json['data'] = Data.fromJson(json['data']));
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    data['stateNum'] = this.stateNum;
    data['error'] = this.error;
    if (this.data != null) {
      data['data'] = this.data.toJson();
    }
    return data;
  }
}
